# Classification Algorithms: Logistic Regression and Support Vector Machine

## 1 Explain what is classification and how it is different from regression

Regression use a virtual line to map input features ti ouutpu lables which are numeric values. For example of hight is 5 feet the what will the weight?

While classification is used to classify all input values in multiple classes of the lables. For example weather the person is a boy or girl, weather the given pictire is of animal, bird, human, etc.

So in simple words
To find quantity we use regression
to find class (group) we use classification

## 2 Explain what is Logistic regression, its working and how it is different from linear regression

Logistic regression is a classification technique, which is used to divide data in various classes. It is mostly used for binary classification. 


Normally in linear regression we use a virtual stright line to map the values, while in logistic regression we use signum or softmax function to map output values in 0 or 1 and probability respectively. 

## 3 Explain what is Linear SVM and its working

Support vector machine is a liner classification and regression technique. It identify the plane or line which can divide data set in to to or multiple parts.

It also find the separator line sucg that the 1st nearest points on eithe side has maximum distance from the line/plane. The points which are closeset to the line are known as support vectors. The distance between two support vectors on eithr side is known as margin.

## 4 What do you mean by kernel functions?

In many clases data can not be separated by a line or a plane. So it is not possible to apply linear classification techniques.

Kernel Functions are the set of the transfer functions which can map input data space to some other dimentional data space where it is easily possible to differentiatle different class by a plane in miltiple domention space.

It is used with SVM (Support Vector Machine) to map the data in separable form.

## 5 Discuss how SVM makes use of kernel functions

Kernel Function is et of functions whch are used to take data as input and transform it into the required form of processing data. It is used due to a set of mathematical functions used in Support Vector Machine providing the method to manipulate the data.

So, Kernel Function generally transforms the training set so that a decision surface is able to transform to a linear equation where dimensions are increased sompare to input data. 

Polynomial kernel, Gaussian kernel, Gaussian radial basis function (RBF), Laplace RBF kernel, Hyperbolic tangent kernel, Sigmoid kernel are some of the examples of various kernel functions.

## 6 Discuss the following terms: Accuracy, Precision, Recall, F1 score, Specificity, Sensitivity, AUROC, PRAUC

Accuracy: It measures how many observations, both positive and negative, were correctly identified.

Precision: Precision is the ratio of the correctly positive labeled by our program to all positive labeled data.

Recall: Precision is the ratio of the correctly positive labeled by diabetic in reality.

F1 score: it combines precision and recall into one metric by calculating the harmonic mean between those two. 

Specificity:Specificity is the correctly negative labeled by the program to all who are healthy in reality.

Sensitivity: Sensitivity is the metric that evaluates a model's ability to predict true positives of each available category.

AUROC: AUC stands for "Area under the ROC Curve. The Area Under the Curve (AUC) is the measure of the ability of a classifier to distinguish between classes and is used as a summary of the ROC curve.

PRAUC: It is a curve that combines precision (PPV) and Recall (TPR) in a single visualization. For every threshold, you calculate PPV and TPR and plot it. The higher on y-axis your curve is the better your model performance. This can be interpreted as the probability that a random positive is assigned a higher score than a random negative.

## 7 perform classification on zoo dataset from kaggle using logistic regression after performing appropriate data pre processing and hyper parameter tuning and evaluate using the technique you feel is fit for this task and give your comments.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,cross_validate, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import svm
import numpy as np

In [ ]:
Data_Link_Class='/content/drive/Othercomputers/My Laptop/Sem 2/257 Machine Learning Shim/Home Work/HW 4/class.csv'
Data_Link_Zoo='/content/drive/Othercomputers/My Laptop/Sem 2/257 Machine Learning Shim/Home Work/HW 4/zoo.csv'

In [ ]:
Zoo=pd.read_csv(Data_Link_Zoo)
#Zoo.info()
#Zoo.isnull().sum().sum()
Zoo.head()

In [ ]:
Zoo.describe()

In [ ]:
# use covariance to check relation between each feature with other with pearson correlation matrix
corrs=Zoo.corr()
plt.figure(figsize=(16,16))
sns.heatmap(corrs,annot=True,fmt='0.2f',center=0)

In [ ]:
Class=pd.read_csv(Data_Link_Class)
Class.head(10)

In [ ]:
Zoo.loc[:,'class_type'].unique()

In [ ]:
Zoo.loc[:,'class_type'].value_counts()

In [ ]:
Zoo.loc[:,'animal_name'].unique()

In [ ]:
Zoo.loc[:,'animal_name'].value_counts()

In [ ]:
X=Zoo.iloc[:,1:-1]
y=Zoo.iloc[:,-1]
X.head()
#y.head()

In [ ]:
#Splitting the data into 75% training and 25% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

X_train = X_train.reset_index(drop = True)
X_test = X_test.reset_index(drop = True)
y_train = y_train.reset_index(drop = True)
y_test = y_test.reset_index(drop = True)

print("size of X_train is: ", X_train.shape)
print("size of X_test is: ", X_test.shape)
print("size of y_train is: ", y_train.shape)
print("size of y_test is: ", y_test.shape)

In [ ]:
#Training the model
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)
y_train_pred = model.predict(X_train)

In [ ]:
print(classification_report(y_train, y_train_pred))

In [ ]:
confusion_matrix(y_train, y_train_pred)

In [ ]:
y_test_pred = model.predict(X_test)
print(classification_report(y_test, y_test_pred))

In [ ]:
confusion_matrix(y_test, y_test_pred)

In [ ]:
# Now instead of train and test set, using cross validation
model = LogisticRegression(random_state=42)
scores = cross_validate(model, X, y, cv = 4, scoring = 'accuracy', return_train_score = True)
scores

In [ ]:
Sus=(y[y==3].index.values)
Sus_df=pd.DataFrame()
for i in Sus:
  print(Zoo.loc[i],i)

*** With less number of iteration for the training the accuracy is low, but as number of iterations are increased the accuracy is also increased. However, after certain number the performance is steady state.

In the data there is one outlier in catagory three (3) which is not able to fit in model. The data which has catagory 3 has been displayed in above code.

# With hyperparameter tunning

In [ ]:
param_grid = [    
    {'penalty' : ['l1', 'l2', 'elasticnet', 'none'],
    'C' : np.logspace(-8, 8, 5),
    'solver' : ['lbfgs','newton-cg','liblinear','sag'],
    'max_iter' : [100,500,1000,2000]
    }
]

clf_h = GridSearchCV(model, param_grid = param_grid, cv = 5)

In [ ]:
best_clf = clf_h.fit(X_train, y_train)

In [ ]:
print('best_clf.best_estimator_: \n',best_clf.best_estimator_)
print("best_clf.best_params_ :\n ",best_clf.best_params_)

In [ ]:
y_train_pred_h = clf_h.predict(X_train)
print(confusion_matrix(y_train, y_train_pred_h))

In [ ]:
y_test_pred_h = clf_h.predict(X_test)
print(classification_report(y_test, y_test_pred_h))
print(confusion_matrix(y_test, y_test_pred_h))

### In case of using hyperparameter tunning the performance can not be improved because of data is limited. (only 100 entris). However, in case of more data set performance can be improved.

## 8 perform classification on MNIST dataset using Linear SVM and then using Kernels and compare the methods

In [ ]:
Data_Test='/content/drive/Othercomputers/My Laptop/Sem 2/257 Machine Learning Shim/Home Work/HW 4/test.csv'
Data_Train='/content/drive/Othercomputers/My Laptop/Sem 2/257 Machine Learning Shim/Home Work/HW 4/train.csv'

In [ ]:
df=pd.read_csv(Data_Train)
#df.info()
#df.describe()
df.head()

In [ ]:
X=df.iloc[:,1:]
y=df.iloc[:,0:1]

# Splitting into train and test
X_train1, X_test1, y_train1, y_test1 = train_test_split(X,y,test_size = 0.12, random_state = 100)

X_train1 = X_train1.reset_index(drop = True)
X_tes1t1 = X_test1.reset_index(drop = True)
y_train1 = y_train1.reset_index(drop = True)
y_test1 = y_test1.reset_index(drop = True)

print("size of X_train is: ", X_train1.shape)
print("size of X_test is: ", X_test1.shape)
print("size of y_train is: ", y_train1.shape)
print("size of y_test is: ", y_test1.shape)

In [ ]:
# Training a linear support vector machine
clf = svm.SVC(kernel='linear',max_iter=1000,random_state=42)
clf.fit(X_train1,y_train1)

In [ ]:
y_train_pred1 = clf.predict(X_train1)

In [ ]:
confusion_matrix(y_train1, y_train_pred1)

array([[3628,    0,    0,    0,    0,    1,    0,    0,    0,    0],
       [   0, 4139,    0,    0,    0,    0,    0,    0,    6,    0],
       [  10,   16, 3519,   39,   15,    4,    9,   13,   39,    2],
       [  17,   26,  160, 3255,    0,  197,    0,    5,  192,   14],
       [   1,    8,    7,    1, 3297,    0,    0,    1,    0,  285],
       [  23,   29,   39,  220,   23, 2892,   29,    0,   67,    4],
       [   8,    5,   32,    5,   11,   21, 3559,    0,    0,    0],
       [   3,   18,   48,   19,   30,    0,    1, 3251,    1,  514],
       [  18,   68,   68,  154,   13,   99,    7,    9, 3091,   18],
       [  19,   18,   28,   51,  435,   12,    1,  319,   23, 2751]])

In [ ]:
y_test_pred1 = clf.predict(X_test1)

In [ ]:
print(classification_report(y_test1, y_test_pred1))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97       503
           1       0.94      0.98      0.96       539
           2       0.86      0.90      0.88       511
           3       0.84      0.83      0.83       485
           4       0.80      0.88      0.84       472
           5       0.83      0.83      0.83       469
           6       0.96      0.94      0.95       496
           7       0.89      0.79      0.83       516
           8       0.85      0.79      0.82       518
           9       0.76      0.78      0.77       531

    accuracy                           0.87      5040
   macro avg       0.87      0.87      0.87      5040
weighted avg       0.87      0.87      0.87      5040



In [ ]:
confusion_matrix(y_test1, y_test_pred1)

array([[494,   0,   1,   0,   0,   6,   2,   0,   0,   0],
       [  0, 528,   2,   4,   0,   0,   0,   3,   2,   0],
       [  3,   4, 460,   7,   9,   3,   3,   6,  15,   1],
       [  1,   2,  16, 401,   0,  33,   0,   1,  27,   4],
       [  1,   1,   5,   3, 416,   0,   3,   3,   1,  39],
       [  5,   4,   7,  33,   8, 388,   6,   0,  14,   4],
       [  4,   2,   9,   0,   4,   6, 467,   0,   4,   0],
       [  3,   3,  11,   4,   9,   1,   0, 406,   1,  78],
       [  4,  14,  21,  23,   7,  29,   6,   4, 409,   1],
       [  2,   1,   3,   3,  66,   2,   0,  34,   8, 412]])

In [ ]:
df2=pd.read_csv(Data_Test)
df2.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [ ]:
y_test_pred2 = clf.predict(df2)

In [ ]:
clf2= svm.SVC(kernel='poly',max_iter=1000,random_state=42)
clf2.fit(X_train1,y_train1)
y_train_pred2 = clf2.predict(X_train1)
print(confusion_matrix(y_train1, y_train_pred2))
y_test_pred2 = clf2.predict(X_test1)
print(classification_report(y_test1, y_test_pred2))
print(confusion_matrix(y_test1, y_test_pred2))

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:289: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  ConvergenceWarning,


[[3613    0    2    0    1    4    5    1    2    1]
 [   0 4125    4    1    4    2    0    5    3    1]
 [   0   12 3635    0    5    1    0   10    1    2]
 [   0    6    5 3821    0   15    0    9    3    7]
 [   2   13    0    0 3568    0    3    2    0   12]
 [   2    2    0    4    0 3310    6    0    2    0]
 [   2    7    0    0    4    3 3624    0    1    0]
 [   0   27   10    0    4    1    0 3834    0    9]
 [   1   12    1    4    5    7    2    1 3509    3]
 [   3   11    0    5   15    6    0   20    2 3595]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       503
           1       0.98      0.99      0.98       539
           2       0.97      0.98      0.98       511
           3       0.97      0.97      0.97       485
           4       0.96      0.97      0.96       472
           5       0.95      0.97      0.96       469
           6       0.99      0.99      0.99       496
           7       0.97      0.97   

In [ ]:
clf3= svm.SVC(kernel='rbf',max_iter=1000,random_state=42)
clf3.fit(X_train1,y_train1)
y_train_pred3 = clf3.predict(X_train1)
print(confusion_matrix(y_train1, y_train_pred3))
y_test_pred3 = clf3.predict(X_test1)
print(classification_report(y_test1, y_test_pred3))
print(confusion_matrix(y_test1, y_test_pred3))

In [ ]:
clf4= svm.SVC(kernel='sigmoid',max_iter=1000,random_state=42)
clf4.fit(X_train1,y_train1)
y_train_pred4 = clf4.predict(X_train1)
print(confusion_matrix(y_train1, y_train_pred4))
y_test_pred4 = clf4.predict(X_test1)
print(classification_report(y_test1, y_test_pred4))
print(confusion_matrix(y_test1, y_test_pred4))

#Performance comparation

#kernel--------'linear'--------'poly'------'rbf'--------'sigmoid'
#Accuracy----87%----------97%--------98%-------79%

As per the above data, it can be shown that compare to sigmoid and linear, poly and rbf can provide beter accuracy. Same can be also visualized in confucion matrix.